### PR TITLE
fix: make rip handle pre-releases more similar to pip

### PR DESCRIPTION
**Pull request by wolfv**
should fix https://github.com/prefix-dev/rip/issues/118

Not sure about #4 but also not sure wether #4 is according to spec, either :)

### CODE REVIEW

**Comment by wolfv** [comment]
Hm, while this works to some degree, it currently thinks that there are no candidates other than pre-releases too often. This is because not all "artifacts" are passed into the `filter_candidates` function. We need to pass in some extra information from the outside or make this filtering different I believe.

**Comment by wolfv** [comment]
I have worked a little more this morning on the pre-release stuff and there is a little problem. Maybe you have ideas. I believe the idea for filtering pre-releases is that it depends on the requirement, for example if I do rip jupyterlab==4.1.0b0 we would only select pre-release candidates for jupyterlab, and so it should be allowed. 

However, the `get_candidates` function only gets a NameId and doesn't know about the spec it came from.

**Comment by notatallshaw** [comment]
> Hm, while this works to some degree, it currently thinks that there are no candidates other than pre-releases too often.

Are you basing this off what Pip does? Because I'm fairly confident Pip is not spec compliant (e.g. https://github.com/pypa/pip/issues/12469) and it's behavior may change quite a bit after https://github.com/pypa/pip/issues/11715 finally lands.

**Comment by wolfv** [comment]
Yeah, indeed, I was trying to see what pip does. I also thought that your interpretation from the linked issue is correct. Unfortunately that is also harder for us to implement (not because the code would be complex, but because our API interfaces don't really support this yet).

The rule we consider implemeting is to allow pre-releases if the version specifier mentions pre-releases, e.g. `jupyterlab==4.1.0b0` would work. `jupyterlab==4.1` would not work. But apparently that wouldn't be spec compliant ... we'll think further on this :)

**Comment by tdejager** [comment]
> Hm, while this works to some degree, it currently thinks that there are no candidates other than pre-releases too often. This is because not all "artifacts" are passed into the `filter_candidates` function. We need to pass in some extra information from the outside or make this filtering different I believe.

What do you mean with this, can you give an example what would and what would not be passed?

**Comment by wolfv** [comment]
The filter candidates function gets artifacts only for a single version. To check if all versions of a given package are pre-releases I moved the function one level up (check last commit).

**Review by tdejager — APPROVED** [review]

**Pull request closed without merging**
